Handle edge cases: Unscrubbed disk and script not running as root
- Unless we are running as root, use sudo.
- If the disk has never been scrubbed, set last scrub to epoch.

diff --git a/check_zpool_scrub b/check_zpool_scrub
--- a/check_zpool_scrub
+++ b/check_zpool_scrub
@@ -149,7 +149,13 @@ STATE_CRITICAL=2
 STATE_UNKNOWN=3
 
 _last_scrub_date() {
-	zpool history | \
+	if [ $(id -u) -eq 0 ]; then
+		zpool_cmd="zpool"
+	else
+		zpool_cmd="sudo zpool"
+	fi
+	eval "$zpool_cmd history >/dev/null" || echo "FAIL"
+	eval "$zpool_cmd history" | \
 		grep "zpool scrub $1" | \
 		grep -v 'zpool scrub -s' | \
 		tail -n 1 | \
@@ -161,7 +167,15 @@ _date_to_timestamp() {
 }
 
 _get_last_scrub() {
-	echo "$(_date_to_timestamp "$(_last_scrub_date "$1")")"
+	last_scrub_date="$(_last_scrub_date "$1")"
+	case "$last_scrub_date" in
+	FAIL*)
+		echo -1 ;;
+	"") # Never been scrubbed
+		echo "$(_date_to_timestamp 1970-01-01)" ;;
+	*)
+		echo "$(_date_to_timestamp "$last_scrub_date")" ;;
+	esac
 }
 
 _performance_data() {
@@ -301,6 +315,11 @@ fi
 
 DATE=$(date +%Y-%m-%dT%H:%M:%SZ --date @$LAST_SCRUB)
 
-echo "$MESSAGE The last scrub on zpool “${OPT_POOL}” was performed on $DATE $(_performance_data)"
+if [ $LAST_SCRUB = -1 ]; then
+	RETURN=$STATE_UNKNOWN
+	echo "UNKNOWN: Failed to run zpool history"
+else
+	echo "$MESSAGE The last scrub on zpool “${OPT_POOL}” was performed on $DATE $(_performance_data)"
+fi
 
 exit $RETURN
