Test options

diff --git a/check_zpool_scrub b/check_zpool_scrub
--- a/check_zpool_scrub
+++ b/check_zpool_scrub
@@ -30,24 +30,26 @@ https://exchange.nagios.org/directory/Plugins/System-Metrics/File-System/check_z
 VERSION=1.0
 FIRST_RELEASE=2016-09-08
 SHORT_DESCRIPTION='Monitoring plugin to check how long ago the last ZFS scrub was performed.'
-USAGE="check_zfs_scrub v$VERSION
+USAGE="check_zpool_scrub v$VERSION
 Copyright (c) $(date +%Y --date=$FIRST_RELEASE)-$(date +%Y) Josef Friedrich <josef@friedrich.rocks>
 
 $SHORT_DESCRIPTION
 
 
-Usage: check_zfs_scrub <options>
+Usage: check_zpool_scrub <options>
 
 Options:
-  -c, --critical=INTERVAL_CRITICAL
+  -c, --critical=OPT_CRITICAL
     Interval in seconds for critical state.
-  -p,--pool=POOL
+  -p,--pool=OPT_POOL
     Name of the pool
   -h, --help
     Show this help.
   -s, --short-description
     Show a short description / summary.
-  -w, --warning=INTERVAL_WARNING
+  -v, --version
+    Show the version number.
+  -w, --warning=OPT_WARNING
     Interval in seconds for warning state. Must be lower than -c.
 
 Performance data:
@@ -64,6 +66,81 @@ Performance data:
   - time
       Time to go in minutes
 "
+
+_getopts() {
+	while getopts ':c:hp:svw:-:' OPT ; do
+		case $OPT in
+			c) OPT_CRITICAL=$OPTARG ;;
+			h) echo "$USAGE" ; exit 0 ;;
+			p) OPT_POOL="$OPTARG" ;;
+			s) echo "$SHORT_DESCRIPTION" ; exit 0 ;;
+			v) echo "$VERSION" ; exit 0 ;;
+			w) OPT_WARNING=$OPTARG ;;
+
+			\?)
+				echo "Invalid option “-$OPTARG”!" >&2
+				exit 2
+				;;
+
+			:)
+				echo "Option “-$OPTARG” requires an argument!" >&2
+				exit 3
+				;;
+
+			-)
+				LONG_OPTARG="${OPTARG#*=}"
+
+				case $OPTARG in
+
+					critical=?*)
+						OPT_CRITICAL=$LONG_OPTARG
+						;;
+
+					help)
+						echo "$USAGE"
+						exit 0
+						;;
+
+					pool=?*)
+						OPT_POOL="$LONG_OPTARG"
+						;;
+
+					short-description)
+						echo "$SHORT_DESCRIPTION"
+						exit 0
+						;;
+
+					version)  echo "$VERSION" ; exit 0 ;;
+
+					warning=?*)
+						OPT_WARNING=$LONG_OPTARG
+						;;
+
+					help*|short-description*|version*)
+						echo "No argument allowed for the option “--$OPTARG”!" >&2
+						exit 4
+						;;
+
+					critical*|pool*|warning*)
+						echo "Option “--$OPTARG” requires an argument!" >&2
+						exit 3
+						;;
+
+					'')	# "--" terminates argument processing
+						break
+						;;
+
+					*)
+						echo "Invalid option “--$OPTARG”!" >&2
+						exit 2
+						;;
+
+				esac
+				;;
+
+		esac
+	done
+}
 
 # Exit codes
 STATE_OK=0
@@ -90,8 +167,8 @@ _get_last_scrub() {
 _performance_data() {
 	echo "| \
 last_ago=$DIFF \
-warning=$INTERVAL_WARNING \
-critical=$INTERVAL_CRITICAL \
+warning=$OPT_WARNING \
+critical=$OPT_CRITICAL \
 progress=$PROGRESS \
 speed=$SPEED \
 time=$TIME"
@@ -175,133 +252,46 @@ _time() {
 	fi
 }
 
-_getopts() {
-	while getopts ':c:hp:sw:-:' OPT ; do
-		case $OPT in
-			c)
-				INTERVAL_CRITICAL=$OPTARG
-				;;
-
-			h)
-				echo "$USAGE"
-				exit 0
-				;;
-
-			p)
-				POOL="$OPTARG"
-				;;
-
-			s)
-				echo "$SHORT_DESCRIPTION"
-				;;
-
-			w)
-				INTERVAL_WARNING=$OPTARG
-				;;
-
-			\?)
-				echo "Invalid option “-$OPTARG”!" >&2
-				exit 2
-				;;
-
-			:)
-				echo "Option “-$OPTARG” requires an argument!" >&2
-				exit 3
-				;;
-
-			-)
-				LONG_OPTARG="${OPTARG#*=}"
-
-				case $OPTARG in
-
-					critical=?*)
-						INTERVAL_CRITICAL=$LONG_OPTARG
-						;;
-
-					help)
-						echo "$USAGE"
-						exit 0
-						;;
-
-					pool=?*)
-						POOL="$LONG_OPTARG"
-						;;
-
-					short-description)
-						echo "$SHORT_DESCRIPTION"
-						exit 0
-						;;
-
-					warning=?*)
-						INTERVAL_WARNING=$LONG_OPTARG
-						;;
-
-					help*|short-description*)
-						echo "No argument allowed for the option “--$OPTARG”!" >&2
-						exit 4
-						;;
-
-					critical*|pool*|warning*)
-						echo "Option “--$OPTARG” requires an argument!" >&2
-						exit 3
-						;;
-
-					'')	# "--" terminates argument processing
-						break
-						;;
-
-					*)
-						echo "Invalid option “--$OPTARG”!" >&2
-						exit 2
-						;;
-
-				esac
-				;;
-
-		esac
-	done
-}
-
 ## This SEPARATOR is required for test purposes. Please don’t remove! ##
 
 _getopts $@
 
-if [ -z "$INTERVAL_WARNING" ]; then
+if [ -z "$OPT_WARNING" ]; then
 	# 1 month 60*60*24*31
-	INTERVAL_WARNING=2678400
+	OPT_WARNING=2678400
 fi
 
-if [ -z "$INTERVAL_CRITICAL" ]; then
+if [ -z "$OPT_CRITICAL" ]; then
 	# 2 month 60*60*24*31*2
-	INTERVAL_CRITICAL=5356800
+	OPT_CRITICAL=5356800
 fi
 
-if ! zpool status "$POOL" > /dev/null 2>&1; then
-	echo "“$POOL” is no ZFS pool!" >&2
+if ! zpool status "$OPT_POOL" > /dev/null 2>&1; then
+	echo "“$OPT_POOL” is no ZFS pool!" >&2
 	echo "$USAGE" >&2
 	exit $STATE_UNKNOWN
 fi
 
 NOW=$(date +%s)
-LAST_SCRUB=$(_get_last_scrub "$POOL")
+LAST_SCRUB=$(_get_last_scrub "$OPT_POOL")
 DIFF=$((NOW - LAST_SCRUB))
 
-if [ "$INTERVAL_WARNING" -gt "$INTERVAL_CRITICAL" ]; then
+if [ "$OPT_WARNING" -gt "$OPT_CRITICAL" ]; then
 	echo '<warntime> must be smaller than <crittime>' >&2
 	_usage  >&2
 	exit $STATE_UNKNOWN
 fi
 
-PROGRESS=$(_progress "$POOL")
-SPEED="$(_speed "$POOL")"
-TIME="$(_time "$POOL")"
+PROGRESS=$(_progress "$OPT_POOL")
+SPEED="$(_speed "$OPT_POOL")"
+TIME="$(_time "$OPT_POOL")"
 
 RETURN=STATE_UNKNOWN
 
-if [ "$DIFF" -gt "$INTERVAL_CRITICAL" ]; then
+if [ "$DIFF" -gt "$OPT_CRITICAL" ]; then
 	RETURN=$STATE_CRITICAL
 	MESSAGE="CRITICAL:"
-elif [ "$DIFF" -gt "$INTERVAL_WARNING" ]; then
+elif [ "$DIFF" -gt "$OPT_WARNING" ]; then
 	RETURN=$STATE_WARNING
 	MESSAGE="WARNING:"
 else
@@ -311,6 +301,6 @@ fi
 
 DATE=$(date +%Y-%m-%dT%H:%M:%SZ --date @$LAST_SCRUB)
 
-echo "$MESSAGE The last scrub on zpool “${POOL}” was performed on $DATE $(_performance_data)"
+echo "$MESSAGE The last scrub on zpool “${OPT_POOL}” was performed on $DATE $(_performance_data)"
 
 exit $RETURN
